[build]
  base    = "frontend"
  command = "npm run build"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "20"

# официальный плагин Netlify для Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
